language: ruby

matrix:
  include:
    - name: "Mongoid 5 on Ruby 2.3.8"
      rvm: 2.3.8
      gemfile: gemfiles/mongoid_5.gemfile
    - name: "Mongoid 5 on Ruby 2.4.9"
      rvm: 2.4.9
      gemfile: gemfiles/mongoid_5.gemfile
    - name: "Mongoid 5 on Ruby 2.5.7"
      rvm: 2.5.7
      gemfile: gemfiles/mongoid_5.gemfile
    - name: "Mongoid 5 on Ruby 2.6.5"
      rvm: 2.6.5
      gemfile: gemfiles/mongoid_5.gemfile
    - name: "Mongoid 5 on JRuby 9.2.7.0"
      rvm: jruby-9.2.7.0
      gemfile: gemfiles/mongoid_5.gemfile
    - name: "Mongoid 7 on Ruby 2.4.9"
      rvm: 2.4.9
      gemfile: gemfiles/mongoid_7.gemfile
    - name: "Mongoid 7 on Ruby 2.5.7"
      rvm: 2.5.7
      gemfile: gemfiles/mongoid_7.gemfile
    - name: "Mongoid 7 on Ruby 2.6.5"
      rvm: 2.6.5
      gemfile: gemfiles/mongoid_7.gemfile
    - name: "Mongoid 7 on Ruby 2.7.0"
      rvm: 2.7.0
      gemfile: gemfiles/mongoid_7.gemfile
    - name: "Mongoid 7 on JRuby 9.2.9.0"
      rvm: jruby-9.2.9.0
      gemfile: gemfiles/mongoid_5.gemfile

  allow_failures:
    - rvm: jruby-9.2.9.0
    - rvm: 2.3.8

jdk:
  - openjdk8

bundler_args: --without development

services:
- mongodb

sudo: false

# Gitter integration
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/4d6749e48eb60321640e
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
